vocabolario/code/Vocabolario/AnalizzaVocabolario/urls.py
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'AnalizzaVocabolario'


urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('register', views.UserCreateView.as_view(), name='user-register'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('personalText', views.PersonalTextList, name='personal-text'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modificauser'),
    path('modificaPassword', views.PasswordChangeView, name='modica-password'),
    path('deleteText', views.DeleteText.as_view(), name='delete-text'),
    path('addText', views.add_text, name='add-text'),
    path('addText/check',  views.check_text_is_unique, name='check-text-unique'),
    path('homepage', views.Homepage, name='homepage'),
    path('analyzeAllWords', views.allwords, name='analyze-all-words'),
    path('analyzeAllPersonalWords', views.allPersonalWords, name='analyze-all-personal-words'),
    path('search', views.search_titles, name='search'),
    path('features/<int:pk>', views.featuresText, name='features-text'),
    path('blacklist', views.blacklist, name='blacklist'),
    path('blacklist/delete',  views.DeleteBlacklist.as_view(), name='delete-blacklist'),
    path('graph/<int:pk>',  views.graphSingleText, name='graph'),
    path('graphPersonalText',  views.graphPersonalText, name='graph-personal-text'),
    path('graphAllText',  views.graphAllText, name='graph-all-text'),
    path('blacklist/return',  views.returnBlacklist, name='return-blacklist'),
    path('select',  views.select_for_compare, name='select-text'),
    path('compare/<int:key_testi1>/<int:key_testi2>',  views.compare_text, name='compare-text'),
    re_path(r'^$', RedirectView.as_view(url='login', permanent=False), name='index')
]

vocabolario/code/Vocabolario/Vocabolario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.views.generic.base import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('AnalizzaVocabolario/', include('AnalizzaVocabolario.urls')),
    re_path(r'^$', RedirectView.as_view(url='AnalizzaVocabolario', permanent=False), name='index')
]

vocabolario/code/Vocabolario/templates/NavBarBase.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
    <link href="{% static 'css/global.css' %}" type="text/css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <link href="http://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="//cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
    <script src="{% static 'js/ajaxSearch.js' %}"></script>
    <title>
        {% block title  %}{% endblock %}
    </title>

</head>
<body>
<div class="container">
    <nav class="navbar" style="display:flex; justify-content: space-between; margin-top: 20px">

        <div align="left">
            <a href="{% url 'AnalizzaVocabolario:homepage' %}">
                <img src="{% static 'img/logo.png' %}"  alt="logo" width="90" >
            </a>
        </div>
        <div class="half-width-centered" style="margin-right: auto; margin-left: auto">
            <div class="navbar-item">
                <div class="searchbar-container"><input id='search' class="form-control" type="search" placeholder="Search" aria-label="Search"></div>
            </div>
        </div>
        <div class="dropdown show">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <i id="icon" class="fas fa-user" style="font-size: 40px"></i>
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                <li><a class="dropdown-item" href="{% url 'AnalizzaVocabolario:profile' user.id %}">Profilo</a></li>
                <li><a class="dropdown-item" href="{% url 'AnalizzaVocabolario:personal-text' %}">Testi personali</a></li>
                <li><a class="dropdown-item" href="{% url 'AnalizzaVocabolario:blacklist' %}">Gestisci blacklist</a></li>
                <li><a class="dropdown-item" href="{% url 'AnalizzaVocabolario:logout' %}">Logout</a></li>
            </ul>
        </div>

    </nav>
    <div>
        {% block content %}

        {% endblock %}
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        new AjaxSearch($('.searchbar-container'));
    });
</script>
{% block script %}{% endblock script %}
</body>
</html>

vocabolario/code/Vocabolario/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <title>
        {% block title  %}

        {% endblock %}
    </title>

</head>
<body>
<div class="container">
    {% block content %}

    {% endblock %}
</div>

{% block javascript %}

{% endblock %}
</body>
</html>

vocabolario/code/Vocabolario/templates/baseList.html
{% extends "NavBarBase.html" %}
{% load static %}
{% block head_title %}  {% endblock %}

{% block content %}
    <div id="div1">
        <h1 align="center" style="padding-bottom: 20px">{% block list_title %} {% endblock %} </h1>
        <table class="table table-striped dataTable" id="Table" style="width:100%">
            {% block colgroup %}{% endblock %}
            <thead>
            <tr>
                {% block table_head %}
                {% endblock %}
            </tr>
            </thead>
            <tbody id="bodytable">
            {% block table_body  %}

            {% endblock %}
            </tbody>
        </table>
    </div>
    <script src="{% static 'js/tableFunction.js' %}"></script>
    <script src="{% static 'js/showWords.js' %}"></script>
{% endblock %}