vocabolario/code/Vocabolario/AnalizzaVocabolario/urls.py
from django.urls import path
from django.urls import re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView

from . import views

app_name = 'AnalizzaVocabolario'


urlpatterns = [
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('register', views.UserCreateView.as_view(), name='user-register'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('personalText', views.PersonalTextList, name='personal-text'),
    path('profile/<int:pk>', views.ShowProfile.as_view(), name='profile'),
    path('modifica/<int:pk>', views.ModifyUser.as_view(), name='modificauser'),
    path('modificaPassword', views.PasswordChangeView, name='modica-password'),
    path('deleteText', views.DeleteText.as_view(), name='delete-text'),
    path('addText', views.add_text, name='add-text'),
    path('addText/check',  views.check_text_is_unique, name='check-text-unique'),
    path('homepage', views.Homepage, name='homepage'),
    path('analyzeAllWords', views.allwords, name='analyze-all-words'),
    path('analyzeAllPersonalWords', views.allPersonalWords, name='analyze-all-personal-words'),
    path('search', views.search_titles, name='search'),
    path('features/<int:pk>', views.featuresText, name='features-text'),
    path('blacklist', views.blacklist, name='blacklist'),
    path('blacklist/delete',  views.DeleteBlacklist.as_view(), name='delete-blacklist'),
    path('graph/<int:pk>',  views.graphSingleText, name='graph'),
    path('graphPersonalText',  views.graphPersonalText, name='graph-personal-text'),
    path('graphAllText',  views.graphAllText, name='graph-all-text'),
    path('blacklist/return',  views.returnBlacklist, name='return-blacklist'),
    path('select',  views.select_for_compare, name='select-text'),
    path('compare/<int:key_testi1>/<int:key_testi2>',  views.compare_text, name='compare-text'),
    re_path(r'^$', RedirectView.as_view(url='login', permanent=False), name='index')
]

vocabolario/code/Vocabolario/Vocabolario/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import re_path
from django.views.generic.base import RedirectView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('AnalizzaVocabolario/', include('AnalizzaVocabolario.urls')),
    re_path(r'^$', RedirectView.as_view(url='AnalizzaVocabolario', permanent=False), name='index')
]

vocabolario/code/Vocabolario/AnalizzaVocabolario/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
# Create your models here.


class Testo(models.Model):
    """Creazione del modello Testo per registrare i testi inseriti"""
    titolo = models.CharField(max_length=120, unique=True)
    link = models.URLField(max_length=250, null=True, blank=True)
    privato = models.BooleanField()
    IC = models.FloatField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    data_creazione = models.DateField(default=timezone.now)

    class Meta:
        verbose_name_plural = 'Testi'

    def __str__(self):
        return self.titolo


class Parola(models.Model):
    """Creazione del modello Parola per salvare tutti i termini presenti nei testi"""
    termine = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Parole'

    def save(self,*args,**kwargs):
        self.termine = self.termine.lower()
        super().save(*args,**kwargs)

    def __str__(self):
        return self.termine


class TestoParola(models.Model):
    """Creazione del modello TestoParola che associa una parola ad un testo"""
    testo = models.ForeignKey(Testo, on_delete=models.CASCADE, related_name='testo')
    parola = models.ForeignKey(Parola, on_delete=models.CASCADE, related_name='parola')
    frequenza = models.IntegerField()


    class Meta:
        verbose_name_plural = 'TestoParole'

class ParolaInBlacklist(models.Model):
    """Creazione del modello ParolaInBlacklist per salvare le parole nell blacklist"""
    parolabl = models.CharField(max_length=120)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'ParoleInBlacklist'

    def save(self,*args,**kwargs):
        self.parolabl = self.parolabl.lower()
        super().save(*args,**kwargs)

vocabolario/code/Vocabolario/AnalizzaVocabolario/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.models import User
from AnalizzaVocabolario.models import Testo, Parola, TestoParola, ParolaInBlacklist
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from AnalizzaVocabolario.services.CalculateIC import calculateIC
from AnalizzaVocabolario.services.SplitText import tokenize


class CreateUserForm(UserCreationForm):
    """Forms per creare utente"""

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

class PasswordChange(PasswordChangeForm):
    """Forms per cambiare password utente"""
    helper = FormHelper()
    helper.form_id = 'add_test_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Modifica password'))


class AddtextCrispyForm(forms.Form):
    """Forms per creare un testo privato o publico"""
    titolo = forms.CharField(max_length=120, min_length=3)
    testo = forms.CharField(max_length=1000000, help_text='Incolla qui il tuo testo', widget=forms.Textarea)
    link = forms.URLField(max_length=250, required=False)
    privato = forms.BooleanField(required=False, help_text='Clicca per rendere il testo privato')

    helper = FormHelper()
    helper.form_id = 'add_test_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Aggiungi'))


    def save(self, user):
        data = self.cleaned_data
        complessità= calculateIC(data['testo'])
        testo = Testo(titolo=data['titolo'], link=data['link'], privato=data['privato'], author=user, IC=complessità)
        Testo.save(testo)
        ris = tokenize(data['testo'])
        for k, v in ris.items():
            if Parola.objects.filter(termine=k).exists():
                tp = TestoParola(parola=Parola.objects.get(termine=k), testo=Testo.objects.get(titolo=data['titolo']),
                                 frequenza=v)
                tp.save(force_insert=True)
            else:
                par = Parola(termine=k)
                par.save(force_insert=True)
                tp = TestoParola(parola=Parola.objects.get(termine=k), testo=Testo.objects.get(titolo=data['titolo']),
                                 frequenza=v)
                tp.save(force_insert=True)


class ModifyUserForm(forms.ModelForm):
    """Forms per modificare dati utente """
    helper = FormHelper()
    helper.form_id = 'modify_user_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Salva'))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class AddWordToBlacklist(forms.Form):
    """Forms per mettere una parola in  blacklist
    :param parola:Aggiunge una parola in blackilist """
    parola = forms.CharField(max_length=20, help_text='Inserisci la parola da aggiungere alla blacklist', min_length=1)

    helper = FormHelper()
    helper.form_id = 'add_test_form'
    helper.form_method = 'POST'
    helper.add_input(Submit('submit', 'Inserisci'))

    def save(self, user):
        data = self.cleaned_data
        parolabl = ParolaInBlacklist(parolabl=data['parola'], user=user)
        ParolaInBlacklist.save(parolabl)

vocabolario/code/Vocabolario/AnalizzaVocabolario/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, View
from django.core import serializers
from AnalizzaVocabolario.forms import CreateUserForm, AddtextCrispyForm, ModifyUserForm, PasswordChange, \
    AddWordToBlacklist
from AnalizzaVocabolario.models import Testo, TestoParola, ParolaInBlacklist
from django.shortcuts import render, redirect
from django.db.models import Q


# Create your views here.

@login_required()
def search_titles(request):
    """QUESTO METODO CI SERVE PER TROVARE DEI TESTI TRAMITE IL TITOLO"""
    # request should be ajax and method should be GET.
    if request.is_ajax and request.method == "GET":
        filtro = request.GET.get("filtro", None)
        if Testo.objects.filter(titolo__contains=filtro).exists():
            testi_list = Testo.objects.filter(titolo__contains=filtro).filter(Q(privato=False) | Q(author=request.user))
            testi = serializers.serialize('json', testi_list, fields=('author_id', 'id', 'link', 'titolo'))
            return JsonResponse(testi, status=200, safe=False)
        else:
            return JsonResponse({'status': False}, status=200)
    return JsonResponse({}, status=400)



class UserCreateView(CreateView):
    """QUESTA CLASSE CI SERVE PER LA CREAZIONE DI UN NUOVO UTENTE"""
    form_class = CreateUserForm
    template_name = 'registration/create_user.html'
    success_url = reverse_lazy('AnalizzaVocabolario:login')


@login_required()
def PersonalTextList(request):
    """QUESTO METODO CI SERVE PER CARICARE I TESTI PERSONALI"""
    testi = Testo.objects.filter(author=request.user).order_by('id').reverse()
    return render(request, 'AnalizzaVocabolario/personalText.html', {'object_list': testi})


@login_required()
def Homepage(request):
    """QUESTO METODO CI SERVE PER CARICARE I TESTI NEL HOMEPAGE"""
    testi = Testo.objects.filter(Q(privato=False) | Q(author=request.user)).order_by('id').reverse()[:10]
    return render(request, 'AnalizzaVocabolario/homepage.html', {'object_list': testi})


class DeleteText(LoginRequiredMixin, DeleteView):
    """QUESTA CLASSE CI SERVE PER ELIMINARE UN TESTO"""
    def get(self, request):
        id1 = request.GET.get('id', None)
        Testo.objects.get(id=id1).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)


@login_required()
def add_text(request):
    """QUESTO METODO CI SERVE PER AGGIUNGERE UN TESTO """
    if request.method == "POST":
        form = AddtextCrispyForm(request.POST)
        if form.is_valid():
            form.save(request.user)

        return redirect('AnalizzaVocabolario:homepage')
    else:
        form = AddtextCrispyForm()
        return render(request, 'AnalizzaVocabolario/addText.html', {'form': form})


@login_required()
def featuresText(request, pk):
    """QUESTO METODO CI SERVE PER ACCEDERE AI FEATURES DI UN  TESTO """
    testoparola = TestoParola.objects.filter(testo_id=pk)
    return render(request, 'AnalizzaVocabolario/featuresText.html', {'object_list': testoparola})

@login_required()
def allwords(request):
    """QUESTO METODO CI SERVE PER ANALIZZARE TUTTI I TESTI"""
    return_dict = dict()
    testoparola = TestoParola.objects.all()
    for p in testoparola:
        if (return_dict.get(p.parola.termine, None)==None):
            return_dict.update({p.parola.termine:p.frequenza})
        else:
            return_dict[p.parola.termine]+=p.frequenza
    return render(request, 'AnalizzaVocabolario/analyzeAllWords.html', {'object_list': return_dict})


@login_required()
def allPersonalWords(request):
    """QUESTO METODO CI SERVE PER ANALIZZARE TUTTI I TESTI PERSONALI"""
    return_dict = dict()
    testoparola = TestoParola.objects.filter(Q(testo__author=request.user))
    for p in testoparola:
        if (return_dict.get(p.parola.termine, None)==None):
            return_dict.update({p.parola.termine:p.frequenza})
        else:
            return_dict[p.parola.termine]+=p.frequenza
    return render(request, 'AnalizzaVocabolario/analyzeAllPersonalWords.html', {'object_list': return_dict})



class ShowProfile(LoginRequiredMixin, DetailView):
    """QUESTA CLASSE CI SERVE PER LA VISUALIZZAZIONE DEL PROPRIO PROFILO"""
    model = User
    template_name = 'AnalizzaVocabolario/profile.html'


class ModifyUser(LoginRequiredMixin, UpdateView):
    """QUESTA CLASSE CI SERVE PER LA MODIFICA DEL PROFILO"""
    model = User
    template_name = 'AnalizzaVocabolario/modificauser.html'
    form_class = ModifyUserForm
    success_url = reverse_lazy('AnalizzaVocabolario:profile')

    def get_success_url(self):
        """QUESTO METODO CI SERVE PER MODIFICARE IL PROFILO UTENTE"""
        user_id = self.kwargs['pk']
        return reverse_lazy('AnalizzaVocabolario:profile', kwargs={'pk': user_id})

@login_required()
def PasswordChangeView(request):
    """QUESTO METODO CI SERVE PER CAMBIARE IL PASSWORD DI UTENTE"""
    if request.method == 'POST':
        form = PasswordChange(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('AnalizzaVocabolario:profile', pk=request.user.id)
    else:
        form = PasswordChange(request.user)
    return render(request, 'AnalizzaVocabolario/password_change.html', {'form': form})

@login_required()
def blacklist(request):
    """QUESTO METODO CI SERVE PER CARICARE LE PAROLE DELLA BLACKLIST IN UNA TABELLA"""
    if request.method == "POST":
        form = AddWordToBlacklist(request.POST)
        if form.is_valid():
            form.save(request.user)
        return redirect('AnalizzaVocabolario:blacklist')
    else:
        form = AddWordToBlacklist()

    parole = ParolaInBlacklist.objects.filter(user=request.user).order_by('id').reverse()
    return render(request, 'AnalizzaVocabolario/blacklist.html', {'form': form, 'object_list': parole})


class DeleteBlacklist(LoginRequiredMixin,View):
    """QUESTO METODO CI SERVE PER ELIMINARE LE PAROLE DALLA BLACKLIST"""
    def get(self, request):
        parolaid = request.GET.get('parola', None)
        print(parolaid)
        ParolaInBlacklist.objects.get(id=parolaid).delete()
        data = {
            'deleted': True
        }
        return JsonResponse(data)

@login_required()
def returnBlacklist(request):
    """QUESTO METODO CI SERVE PER ACCEDERE ALLA BLACKLIST"""
    listWords = ParolaInBlacklist.objects.filter(user=request.user)
    list_words = serializers.serialize('json', listWords, fields=('parolabl'))
    return JsonResponse(list_words, status=200, safe=False)


@login_required()
def graphSingleText(request, pk):
    """QUESTO METODO CI SERVE PER VEDERE L'ANALISI GRAFICA DI UN TESTO"""
    titolo = Testo.objects.get(id=pk)
    print(titolo)
    testoparola = TestoParola.objects.filter(testo_id=pk)
    return render(request, 'AnalizzaVocabolario/graph.html', {'object_list': testoparola, 'titolo':titolo})


@login_required()
def graphPersonalText(request):
    """QUESTO METODO CI SERVE PER VEDERE L'ANALISI GRAFICA DI TESTI PERSONALI"""
    return_dict = dict()
    testoparola = TestoParola.objects.filter(Q(testo__author=request.user))
    for p in testoparola:
        if (return_dict.get(p.parola.termine, None)==None):
            return_dict.update({p.parola.termine:p.frequenza})
        else:
            return_dict[p.parola.termine]+=p.frequenza
    return render(request, 'AnalizzaVocabolario/graphPersonalText.html', {'object_list': return_dict})


@login_required()
def graphAllText(request):
    """QUESTO METODO CI SERVE PER VEDERE L'ANALISI GRAFICA DI TUTTI I TESTI"""
    return_dict = dict()
    testoparola = TestoParola.objects.all()
    for p in testoparola:
        if (return_dict.get(p.parola.termine, None)==None):
            return_dict.update({p.parola.termine:p.frequenza})
        else:
            return_dict[p.parola.termine]+=p.frequenza
    return render(request, 'AnalizzaVocabolario/graphAllText.html', {'object_list': return_dict})

@login_required()
def check_text_is_unique(request):
    """QUESTO METODO CI SERVE PER GARANTIRE CHE IL TITOLO SIA UNICO"""
    title = None
    titolo = request.GET.get('titolo', False)
    if titolo:
        title = Testo.objects.filter(titolo=titolo)
    return JsonResponse({'is_not_unique': True if title else False})

@login_required()
def select_for_compare(request):
    """QUESTO METODO CI SERVE PER SELEZIONARE DUE TESTI DA CONFRONTARE"""
    testi = Testo.objects.filter(Q(privato=False) | Q(author=request.user))
    return render(request, 'AnalizzaVocabolario/selectForCompare.html', {'object_list': testi})

@login_required()
def compare_text(request, key_testi1, key_testi2):
    """QUESTO METODO CI SERVE PER CONFRONTARE DUE TESTI"""
    testo1 = TestoParola.objects.filter(testo_id=key_testi1)
    testo2 = TestoParola.objects.filter(testo_id=key_testi2)
    return render(request, 'AnalizzaVocabolario/compare.html', {'testo1': testo1, 'testo2': testo2})

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/addText.html
{% extends 'NavBarBase.html' %}
{% load crispy_forms_tags %}
{% block title  %}Inserisci nuovo testo{% endblock %}
{% block content %}
    <br>
    {% crispy form %}
{% endblock %}
{% block script %}
    <script>
        $('#id_titolo').change(function() {
            console.log($(this).val());
            $.ajax({
                type: 'GET',
                url: '{% url 'AnalizzaVocabolario:check-text-unique' %}',
                data: {
                    'titolo' : $(this).val()
                },
                dataType: "json",
                success: function (data) {
                    if (data.is_not_unique){
                        alert('Esiste già un testo con questo titolo');
                    }
                }
            })
        })
    </script>
{% endblock script %}

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/blacklist.html
{% extends "NavBarBase.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_title %}  {% endblock %}

{% block content %}
    <div style="padding-bottom: 20px">
        <p style="font-size: 25px;  font-family:'Verdana'" class="text-left">BLACKLIST</p>
        <p style="font-size: 15px;" class="text-left">Qui puoi gestire la tua <b>blacklist</b>: una lista di parole che puoi decidere di nascondere mentre analizzi un testo.</p>
    </div>
    <form method="post">{% csrf_token %}
        {% crispy form %}
    </form>
    <table class="table table-striped  dataTable" id="Table">
        <thead>
        <tr>
            <th class="text-center">Parola</th>
            <th class="text-center">Azioni</th>
        </tr>
        </thead>
        <tbody>
        {% for parola in object_list %}
            <tr>
                <td id="{{ parola.parolabl }}" class="text-center">{{ parola.parolabl }}</td>
                <td class="text-center">
                    <a type="button" class="btn btn-danger" onclick="deleteWord({{ parola.id }})"><i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<script>
    function deleteWord(parola) {
        var action = confirm("Vuoi eliminare la parola dalla blacklist?");
        if (action != false) {
            $.ajax({
                url: '{% url "AnalizzaVocabolario:delete-blacklist" %}',
                data: {
                    'parola': parola,
                },
                dataType: 'json',
                success: function (data) {
                    if (data.deleted) {
                        $("#Table #" + parola.parolabl).remove();
                        window.location.reload();
                    }
                }
            })
        }
    }
</script>
{% endblock %}

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/homepage.html
{% extends 'baseList.html' %}
{% block title  %}Homepage{% endblock %}
{% block list_title %}
    <p style="">Benvenuto, <b>{{ user.get_username }}</b></p>
    <p style="font-size: 25px;  font-family:'Verdana'" class="text-left">TESTI RECENTI</p>
    <p style="font-size: 15px;" class="text-left">Ecco una lista degli ultimi 10 testi caricati sulla piattaforma.</p>
{% endblock %}
{{% block colgroup %}
    <colgroup>
        <col width="25%">
        <col width="25%">
        <col width="10%">
        <col width="15%">
        <col width="25%">
    </colgroup>
{% endblock %}
{% block table_head %}
    <th class="text-center">Titolo</th>
    <th class="text-center">Link</th>
    <th class="text-center">Autore</th>
    <th class="text-center">Data creazione</th>
    <th class="text-center">Azioni</th>
{% endblock %}

{% block table_body %}
    <div>
        <a type="button" class="btn btn-info" data-toggle="tooltip" title="Aggiungi un nuovo testo" href="{% url 'AnalizzaVocabolario:add-text' %}"><i class="fas fa-plus-circle"></i></a>
        <a type="button" class="btn btn-success"  data-toggle="tooltip" title="Analizza tutte le parole" href="{% url 'AnalizzaVocabolario:analyze-all-words' %}" ><i class="fas fa-binoculars"></i></a>
        <a type="button" class="btn btn-warning" data-toggle="tooltip" title="Grafico delle parole" style="margin-right: 2px" href="{% url 'AnalizzaVocabolario:graph-all-text' %}" ><i class="fas fa-chart-pie"></i></a>
        <a type="button" class="btn btn-primary" data-toggle="tooltip" title="Confronta due testi" style="margin-top: 2px" href="{% url 'AnalizzaVocabolario:select-text' %}"><i class="fas fa-balance-scale"></i></a>
    </div>
    <br>
    {% for testo in object_list %}
        <tr id="text-{{testo.id}}">
            <td class="text-left">{{ testo.titolo }}</td>
            <td class="text-left"><a href="{{ testo.link }}" target="_blank">{{ testo.link }}</a></td>
            <td class="text-center">{{ testo.author }}</td>
            <td class="text-center">{{ testo.data_creazione }}</td>
            <td class="text-left"><a type="button" data-toggle="tooltip" title="Analizza il testo" class="btn btn-success mr-1" href="{% url 'AnalizzaVocabolario:features-text' testo.id %}"><i class="fas fa-binoculars"></i></a>
                <a type="button" class="btn btn-warning" data-toggle="tooltip" title="Grafico parole '{{ testo.titolo }}'" href="{% url 'AnalizzaVocabolario:graph' testo.id%}"><i class="fas fa-chart-pie"></i></a>
                {% if testo.author.id == user.id %}
                    <button  class="btn btn-danger mr-1" data-toggle="tooltip" title="Elimina '{{ testo.titolo }}'" onClick="deleteText({{testo.id}})"><i class="fas fa-trash-alt"></i></button>
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    <script>
        function deleteText(id) {
            var action = confirm("Sei sicuro di voler eliminare questo testo?");
            if (action != false) {
                $.ajax({
                    url: '{% url "AnalizzaVocabolario:delete-text" %}',
                    data: {
                        'id': id,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.deleted) {
                            $("#Table #text-" + id).remove();
                        }
                    }
                });
            }
        }
    </script>
{% endblock %}

<style type="text/css">

    .floating-right {
        float: right;
    }
</style>

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/modificauser.html
{% extends 'NavBarBase.html' %}
{% load crispy_forms_tags %}
{% block title  %}Modifica profilo {{ object.username }}{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
        {% crispy form %}
    </form>
{% endblock %}

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/personalText.html
{% extends 'baseList.html' %}
{% load static %}

{% block title  %} Testi personali{% endblock %}
{% block colgroup %}
    <colgroup>
        <col width="30%">
        <col width="40%">
        <col width="15%">
        <col width="15%">
    </colgroup>
{% endblock %}
{% block table_head %}
    <th class="text-center">Titolo</th>
    <th class="text-center">Link</th>
    <th class="text-center">Link</th>
    <th class="text-center">Azioni</th>
{% endblock %}
{% block list_title %}
    <p style="font-size: 25px;  font-family:'Verdana'" class="text-left">TESTI PERSONALI</p>
    <p style="font-size: 15px" class="text-left">Qui di seguito trovi una lista contente le informazioni sui testi che hai aggiunto. Utilizza le opzioni per eliminarli o analizzarli.</p>
{% endblock %}
{% block table_body %}
    <div class="bd-highlight">
        <a type="button" class="btn btn-info bd-highlight" data-toggle="tooltip" title="Aggiungi un nuovo testo" href="{% url 'AnalizzaVocabolario:add-text' %}"><i class="fas fa-plus-circle"></i></a>
        <a type="button" class="btn btn-success bd-highlight" data-toggle="tooltip" title="Analizza tutte le parole nei tuoi testi" href="{% url 'AnalizzaVocabolario:analyze-all-personal-words' %}"><i class="fas fa-binoculars"></i></a>
        <a type="button" class="btn btn-warning bd-highlight" data-toggle="tooltip" title="Grafico delle parole nei tuoi testi" style="margin-right: 2px" href="{% url 'AnalizzaVocabolario:graph-personal-text' %}"><i class="fas fa-chart-pie"></i></a>
        <a type="button" class="btn btn-primary bd-highlight" data-toggle="tooltip" title="Confronta due testi" style="margin-top: 2px" href="{% url 'AnalizzaVocabolario:select-text' %}"><i class="fas fa-balance-scale"></i></a>
    </div>
    <br>
    {% for testo in object_list %}
        <tr id="text-{{testo.id}}">
            <td class="text-center">{{ testo.titolo }}</td>
            <td class="text-center"><a href="{{ testo.link }}" target="_blank">{{ testo.link }}</a></td>
            <td class="text-center">{{ testo.data_creazione }}</td>
            <td class="text-center"><a type="button" data-toggle="tooltip" title="Analizza il testo" class="btn btn-success mr-1" href="{% url 'AnalizzaVocabolario:features-text' testo.pk %}"><i class="fas fa-binoculars"></i></a>
                <a type="button" data-toggle="tooltip" title="Grafico parole '{{ testo.titolo }}'" class="btn btn-warning" href="{% url 'AnalizzaVocabolario:graph' testo.id%}"><i class="fas fa-chart-pie"></i></a>
                <button class="btn btn-danger mr-1" data-toggle="tooltip" title="Elimina '{{ testo.titolo }}'" onClick="deleteText({{testo.id}})"><i class="fas fa-trash-alt"></i></button>
            </td>
        </tr>
    {% endfor %}
    <script>
        function deleteText(id) {
            var action = confirm("Sei sicuro di voler eliminare questo testo?");
            if (action != false) {
                $.ajax({
                    url: '{% url "AnalizzaVocabolario:delete-text" %}',
                    data: {
                        'id': id,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.deleted) {
                            $("#Table #text-" + id).remove();
                        }
                    }
                });
            }
        }
    </script>
{% endblock %}

vocabolario/code/Vocabolario/AnalizzaVocabolario/templates/AnalizzaVocabolario/profile.html
{% extends 'NavBarBase.html'%}

{% block title  %} Profilo di {{ object.username }}{% endblock %}

{% block content %}
    <div style="padding-bottom: 20px">
        <p style="font-size: 25px;  font-family:'Verdana'" class="text-left">Gestione profilo</p>
    </div>
    <p>Nome: <b>{{ object.first_name }}</b></p>
    <p>Cognome: <b>{{ object.last_name }}</b></p>
    <p>Username: <b>{{ object.username }}</b></p>
    <p>Email: {{ object.email }}</p>
    <br>
    <a class="btn btn-success mr-5"  href="{% url 'AnalizzaVocabolario:modificauser' user.id %}">Modifica profilo</a>
    <a class="btn btn-success"  href="{% url 'AnalizzaVocabolario:modica-password' %}">Modifica password</a>
{% endblock %}